settings:
  APP_DISPLAY_NAME: $(OVERLAY_APP_DISPLAY_NAME)
  PRODUCTION_APP_NAME: $(OVERLAY_PRODUCTION_APP_NAME)
  APP_GROUP_IDENTIFIER: $(OVERLAY_APP_GROUP_IDENTIFIER)
  BASE_BUNDLE_IDENTIFIER: $(OVERLAY_BASE_BUNDLE_IDENTIFIER)
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: $(OVERLAY_DEVELOPMENT_TEAM)
  PROVISIONING_PROFILE_SPECIFIER: $(OVERLAY_PROVISIONING_PROFILE_SPECIFIER)
  APS_ENVIRONMENT: $(OVERLAY_APS_ENVIRONMENT)

  # Optional configuration to load accounts from Element Classic.
  CLASSIC_APP_GROUP_IDENTIFIER: $(OVERLAY_CLASSIC_APP_GROUP_IDENTIFIER)
  CLASSIC_APP_KEYCHAIN_SERVICE_IDENTIFIER: $(OVERLAY_CLASSIC_APP_KEYCHAIN_SERVICE_IDENTIFIER)
  CLASSIC_APP_KEYCHAIN_ACCESS_GROUP_IDENTIFIER: $(OVERLAY_CLASSIC_APP_KEYCHAIN_ACCESS_GROUP_IDENTIFIER)
  CLASSIC_APP_DEEP_LINK_URL: $(OVERLAY_CLASSIC_APP_DEEP_LINK_URL)
